### ISSUE TITLE
Replace double quote with single quote for _form class in routing.yml

### ISSUE THREAD

**Issue by T2L** [mikeyp/google_tag#14]
This module cannot be installed on environments like Acquia either via command line or the Drupal admin due to the double quoted form class in the routing.yml. Running it through YAML linter returned a malformed error. Changing it to single quotes corrects this issue, and I can now install the module on Acquia.

```
google_tag.settings_form:
  path: "/admin/config/system/google_tag"
  defaults:
    _title: "Google Tag Manager"
    _form: '\Drupal\google_tag\Form\GoogleTagSettingsForm'
  requirements:
    _permission: 'administer google tag manager'
```

Copied from https://www.drupal.org/node/2838151
